### PR TITLE
Upgrade to 2.3.8

### PR DESCRIPTION
**Pull request by shkrt**
Upgrade ruby version to 2.3.8. Availability of 2.3.8 on AWS is not clear, since it does not show patch version. But for staging we can specify github branch, in which chef recipe is located, so we can test it on staging even before merge.

### CODE REVIEW

**Comment by antonzaytsev** [comment]
just tested on jakku,
seems like there is no 2.3.8 version
```
[anton@jakku-app1 ~]$ ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```

**Comment by antonzaytsev** [comment]
here is the url it checked for ruby package https://opsworks-instance-assets-us-east-1.s3.amazonaws.com/packages/amazon/2017.09/opsworks-ruby23-2.3.7-1.x86_64.rpm

**Comment by shkrt** [comment]
did you update the recipe on opsworks? because it is cached by default

**Comment by shkrt** [comment]
updated branch name at opsworks, and now it fails with `Failed to download asset opsworks-ruby23 for Install user space OpsWorks ruby package with url https://opsworks-instance-assets-us-east-1.s3.amazonaws.com/packages/amazon/2017.09/opsworks-ruby23-2.3.8-1.x86_64.rpm` looks like they're not updated ruby package in repository yet

**Comment by antonzaytsev** [comment]
:(

**Comment by ashishtajane** [comment]
😿

**Pull request closed without merging**
